# Generated by Django 6.0.5 on 2026-05-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_at',
            field=models.DateField(blank=True, null=True, verbose_name='data_nascimento'),
        ),
    ]
